module.exports = {
        typeDefs: // Code generated by Prisma (prisma@1.34.10). DO NOT EDIT.
  // Please don't change this file manually but run `prisma generate` to update it.
  // For more information, please read the docs: https://www.prisma.io/docs/prisma-client/

/* GraphQL */ `type AggregateEvent {
  count: Int!
}

type AggregateLocation {
  count: Int!
}

type AggregatePatrol {
  count: Int!
}

type AggregateTroop {
  count: Int!
}

type AggregateUser {
  count: Int!
}

type BatchPayload {
  count: Long!
}

scalar DateTime

type Event {
  id: ID!
  type: String!
  createdAt: DateTime!
  updatedAt: DateTime!
  patrol: Patrol
  troop: Troop
  title: String!
  description: String
  date: DateTime
  time: DateTime
  location: Location
  meetLocation: Location
  startDate: DateTime
  endDate: DateTime
  recurring: Boolean
  day: WEEK_DAY
  distance: Int
  published: Boolean!
  owner: User!
}

type EventConnection {
  pageInfo: PageInfo!
  edges: [EventEdge]!
  aggregate: AggregateEvent!
}

input EventCreateInput {
  id: ID
  type: String!
  patrol: PatrolCreateOneWithoutEventsInput
  troop: TroopCreateOneWithoutEventsInput
  title: String!
  description: String
  date: DateTime
  time: DateTime
  location: LocationCreateOneInput
  meetLocation: LocationCreateOneInput
  startDate: DateTime
  endDate: DateTime
  recurring: Boolean
  day: WEEK_DAY
  distance: Int
  published: Boolean
  owner: UserCreateOneWithoutEventsInput!
}

input EventCreateManyWithoutOwnerInput {
  create: [EventCreateWithoutOwnerInput!]
  connect: [EventWhereUniqueInput!]
}

input EventCreateManyWithoutPatrolInput {
  create: [EventCreateWithoutPatrolInput!]
  connect: [EventWhereUniqueInput!]
}

input EventCreateManyWithoutTroopInput {
  create: [EventCreateWithoutTroopInput!]
  connect: [EventWhereUniqueInput!]
}

input EventCreateWithoutOwnerInput {
  id: ID
  type: String!
  patrol: PatrolCreateOneWithoutEventsInput
  troop: TroopCreateOneWithoutEventsInput
  title: String!
  description: String
  date: DateTime
  time: DateTime
  location: LocationCreateOneInput
  meetLocation: LocationCreateOneInput
  startDate: DateTime
  endDate: DateTime
  recurring: Boolean
  day: WEEK_DAY
  distance: Int
  published: Boolean
}

input EventCreateWithoutPatrolInput {
  id: ID
  type: String!
  troop: TroopCreateOneWithoutEventsInput
  title: String!
  description: String
  date: DateTime
  time: DateTime
  location: LocationCreateOneInput
  meetLocation: LocationCreateOneInput
  startDate: DateTime
  endDate: DateTime
  recurring: Boolean
  day: WEEK_DAY
  distance: Int
  published: Boolean
  owner: UserCreateOneWithoutEventsInput!
}

input EventCreateWithoutTroopInput {
  id: ID
  type: String!
  patrol: PatrolCreateOneWithoutEventsInput
  title: String!
  description: String
  date: DateTime
  time: DateTime
  location: LocationCreateOneInput
  meetLocation: LocationCreateOneInput
  startDate: DateTime
  endDate: DateTime
  recurring: Boolean
  day: WEEK_DAY
  distance: Int
  published: Boolean
  owner: UserCreateOneWithoutEventsInput!
}

type EventEdge {
  node: Event!
  cursor: String!
}

enum EventOrderByInput {
  id_ASC
  id_DESC
  type_ASC
  type_DESC
  createdAt_ASC
  createdAt_DESC
  updatedAt_ASC
  updatedAt_DESC
  title_ASC
  title_DESC
  description_ASC
  description_DESC
  date_ASC
  date_DESC
  time_ASC
  time_DESC
  startDate_ASC
  startDate_DESC
  endDate_ASC
  endDate_DESC
  recurring_ASC
  recurring_DESC
  day_ASC
  day_DESC
  distance_ASC
  distance_DESC
  published_ASC
  published_DESC
}

type EventPreviousValues {
  id: ID!
  type: String!
  createdAt: DateTime!
  updatedAt: DateTime!
  title: String!
  description: String
  date: DateTime
  time: DateTime
  startDate: DateTime
  endDate: DateTime
  recurring: Boolean
  day: WEEK_DAY
  distance: Int
  published: Boolean!
}

input EventScalarWhereInput {
  id: ID
  id_not: ID
  id_in: [ID!]
  id_not_in: [ID!]
  id_lt: ID
  id_lte: ID
  id_gt: ID
  id_gte: ID
  id_contains: ID
  id_not_contains: ID
  id_starts_with: ID
  id_not_starts_with: ID
  id_ends_with: ID
  id_not_ends_with: ID
  type: String
  type_not: String
  type_in: [String!]
  type_not_in: [String!]
  type_lt: String
  type_lte: String
  type_gt: String
  type_gte: String
  type_contains: String
  type_not_contains: String
  type_starts_with: String
  type_not_starts_with: String
  type_ends_with: String
  type_not_ends_with: String
  createdAt: DateTime
  createdAt_not: DateTime
  createdAt_in: [DateTime!]
  createdAt_not_in: [DateTime!]
  createdAt_lt: DateTime
  createdAt_lte: DateTime
  createdAt_gt: DateTime
  createdAt_gte: DateTime
  updatedAt: DateTime
  updatedAt_not: DateTime
  updatedAt_in: [DateTime!]
  updatedAt_not_in: [DateTime!]
  updatedAt_lt: DateTime
  updatedAt_lte: DateTime
  updatedAt_gt: DateTime
  updatedAt_gte: DateTime
  title: String
  title_not: String
  title_in: [String!]
  title_not_in: [String!]
  title_lt: String
  title_lte: String
  title_gt: String
  title_gte: String
  title_contains: String
  title_not_contains: String
  title_starts_with: String
  title_not_starts_with: String
  title_ends_with: String
  title_not_ends_with: String
  description: String
  description_not: String
  description_in: [String!]
  description_not_in: [String!]
  description_lt: String
  description_lte: String
  description_gt: String
  description_gte: String
  description_contains: String
  description_not_contains: String
  description_starts_with: String
  description_not_starts_with: String
  description_ends_with: String
  description_not_ends_with: String
  date: DateTime
  date_not: DateTime
  date_in: [DateTime!]
  date_not_in: [DateTime!]
  date_lt: DateTime
  date_lte: DateTime
  date_gt: DateTime
  date_gte: DateTime
  time: DateTime
  time_not: DateTime
  time_in: [DateTime!]
  time_not_in: [DateTime!]
  time_lt: DateTime
  time_lte: DateTime
  time_gt: DateTime
  time_gte: DateTime
  startDate: DateTime
  startDate_not: DateTime
  startDate_in: [DateTime!]
  startDate_not_in: [DateTime!]
  startDate_lt: DateTime
  startDate_lte: DateTime
  startDate_gt: DateTime
  startDate_gte: DateTime
  endDate: DateTime
  endDate_not: DateTime
  endDate_in: [DateTime!]
  endDate_not_in: [DateTime!]
  endDate_lt: DateTime
  endDate_lte: DateTime
  endDate_gt: DateTime
  endDate_gte: DateTime
  recurring: Boolean
  recurring_not: Boolean
  day: WEEK_DAY
  day_not: WEEK_DAY
  day_in: [WEEK_DAY!]
  day_not_in: [WEEK_DAY!]
  distance: Int
  distance_not: Int
  distance_in: [Int!]
  distance_not_in: [Int!]
  distance_lt: Int
  distance_lte: Int
  distance_gt: Int
  distance_gte: Int
  published: Boolean
  published_not: Boolean
  AND: [EventScalarWhereInput!]
  OR: [EventScalarWhereInput!]
  NOT: [EventScalarWhereInput!]
}

type EventSubscriptionPayload {
  mutation: MutationType!
  node: Event
  updatedFields: [String!]
  previousValues: EventPreviousValues
}

input EventSubscriptionWhereInput {
  mutation_in: [MutationType!]
  updatedFields_contains: String
  updatedFields_contains_every: [String!]
  updatedFields_contains_some: [String!]
  node: EventWhereInput
  AND: [EventSubscriptionWhereInput!]
  OR: [EventSubscriptionWhereInput!]
  NOT: [EventSubscriptionWhereInput!]
}

input EventUpdateInput {
  type: String
  patrol: PatrolUpdateOneWithoutEventsInput
  troop: TroopUpdateOneWithoutEventsInput
  title: String
  description: String
  date: DateTime
  time: DateTime
  location: LocationUpdateOneInput
  meetLocation: LocationUpdateOneInput
  startDate: DateTime
  endDate: DateTime
  recurring: Boolean
  day: WEEK_DAY
  distance: Int
  published: Boolean
  owner: UserUpdateOneRequiredWithoutEventsInput
}

input EventUpdateManyDataInput {
  type: String
  title: String
  description: String
  date: DateTime
  time: DateTime
  startDate: DateTime
  endDate: DateTime
  recurring: Boolean
  day: WEEK_DAY
  distance: Int
  published: Boolean
}

input EventUpdateManyMutationInput {
  type: String
  title: String
  description: String
  date: DateTime
  time: DateTime
  startDate: DateTime
  endDate: DateTime
  recurring: Boolean
  day: WEEK_DAY
  distance: Int
  published: Boolean
}

input EventUpdateManyWithoutOwnerInput {
  create: [EventCreateWithoutOwnerInput!]
  delete: [EventWhereUniqueInput!]
  connect: [EventWhereUniqueInput!]
  set: [EventWhereUniqueInput!]
  disconnect: [EventWhereUniqueInput!]
  update: [EventUpdateWithWhereUniqueWithoutOwnerInput!]
  upsert: [EventUpsertWithWhereUniqueWithoutOwnerInput!]
  deleteMany: [EventScalarWhereInput!]
  updateMany: [EventUpdateManyWithWhereNestedInput!]
}

input EventUpdateManyWithoutPatrolInput {
  create: [EventCreateWithoutPatrolInput!]
  delete: [EventWhereUniqueInput!]
  connect: [EventWhereUniqueInput!]
  set: [EventWhereUniqueInput!]
  disconnect: [EventWhereUniqueInput!]
  update: [EventUpdateWithWhereUniqueWithoutPatrolInput!]
  upsert: [EventUpsertWithWhereUniqueWithoutPatrolInput!]
  deleteMany: [EventScalarWhereInput!]
  updateMany: [EventUpdateManyWithWhereNestedInput!]
}

input EventUpdateManyWithoutTroopInput {
  create: [EventCreateWithoutTroopInput!]
  delete: [EventWhereUniqueInput!]
  connect: [EventWhereUniqueInput!]
  set: [EventWhereUniqueInput!]
  disconnect: [EventWhereUniqueInput!]
  update: [EventUpdateWithWhereUniqueWithoutTroopInput!]
  upsert: [EventUpsertWithWhereUniqueWithoutTroopInput!]
  deleteMany: [EventScalarWhereInput!]
  updateMany: [EventUpdateManyWithWhereNestedInput!]
}

input EventUpdateManyWithWhereNestedInput {
  where: EventScalarWhereInput!
  data: EventUpdateManyDataInput!
}

input EventUpdateWithoutOwnerDataInput {
  type: String
  patrol: PatrolUpdateOneWithoutEventsInput
  troop: TroopUpdateOneWithoutEventsInput
  title: String
  description: String
  date: DateTime
  time: DateTime
  location: LocationUpdateOneInput
  meetLocation: LocationUpdateOneInput
  startDate: DateTime
  endDate: DateTime
  recurring: Boolean
  day: WEEK_DAY
  distance: Int
  published: Boolean
}

input EventUpdateWithoutPatrolDataInput {
  type: String
  troop: TroopUpdateOneWithoutEventsInput
  title: String
  description: String
  date: DateTime
  time: DateTime
  location: LocationUpdateOneInput
  meetLocation: LocationUpdateOneInput
  startDate: DateTime
  endDate: DateTime
  recurring: Boolean
  day: WEEK_DAY
  distance: Int
  published: Boolean
  owner: UserUpdateOneRequiredWithoutEventsInput
}

input EventUpdateWithoutTroopDataInput {
  type: String
  patrol: PatrolUpdateOneWithoutEventsInput
  title: String
  description: String
  date: DateTime
  time: DateTime
  location: LocationUpdateOneInput
  meetLocation: LocationUpdateOneInput
  startDate: DateTime
  endDate: DateTime
  recurring: Boolean
  day: WEEK_DAY
  distance: Int
  published: Boolean
  owner: UserUpdateOneRequiredWithoutEventsInput
}

input EventUpdateWithWhereUniqueWithoutOwnerInput {
  where: EventWhereUniqueInput!
  data: EventUpdateWithoutOwnerDataInput!
}

input EventUpdateWithWhereUniqueWithoutPatrolInput {
  where: EventWhereUniqueInput!
  data: EventUpdateWithoutPatrolDataInput!
}

input EventUpdateWithWhereUniqueWithoutTroopInput {
  where: EventWhereUniqueInput!
  data: EventUpdateWithoutTroopDataInput!
}

input EventUpsertWithWhereUniqueWithoutOwnerInput {
  where: EventWhereUniqueInput!
  update: EventUpdateWithoutOwnerDataInput!
  create: EventCreateWithoutOwnerInput!
}

input EventUpsertWithWhereUniqueWithoutPatrolInput {
  where: EventWhereUniqueInput!
  update: EventUpdateWithoutPatrolDataInput!
  create: EventCreateWithoutPatrolInput!
}

input EventUpsertWithWhereUniqueWithoutTroopInput {
  where: EventWhereUniqueInput!
  update: EventUpdateWithoutTroopDataInput!
  create: EventCreateWithoutTroopInput!
}

input EventWhereInput {
  id: ID
  id_not: ID
  id_in: [ID!]
  id_not_in: [ID!]
  id_lt: ID
  id_lte: ID
  id_gt: ID
  id_gte: ID
  id_contains: ID
  id_not_contains: ID
  id_starts_with: ID
  id_not_starts_with: ID
  id_ends_with: ID
  id_not_ends_with: ID
  type: String
  type_not: String
  type_in: [String!]
  type_not_in: [String!]
  type_lt: String
  type_lte: String
  type_gt: String
  type_gte: String
  type_contains: String
  type_not_contains: String
  type_starts_with: String
  type_not_starts_with: String
  type_ends_with: String
  type_not_ends_with: String
  createdAt: DateTime
  createdAt_not: DateTime
  createdAt_in: [DateTime!]
  createdAt_not_in: [DateTime!]
  createdAt_lt: DateTime
  createdAt_lte: DateTime
  createdAt_gt: DateTime
  createdAt_gte: DateTime
  updatedAt: DateTime
  updatedAt_not: DateTime
  updatedAt_in: [DateTime!]
  updatedAt_not_in: [DateTime!]
  updatedAt_lt: DateTime
  updatedAt_lte: DateTime
  updatedAt_gt: DateTime
  updatedAt_gte: DateTime
  patrol: PatrolWhereInput
  troop: TroopWhereInput
  title: String
  title_not: String
  title_in: [String!]
  title_not_in: [String!]
  title_lt: String
  title_lte: String
  title_gt: String
  title_gte: String
  title_contains: String
  title_not_contains: String
  title_starts_with: String
  title_not_starts_with: String
  title_ends_with: String
  title_not_ends_with: String
  description: String
  description_not: String
  description_in: [String!]
  description_not_in: [String!]
  description_lt: String
  description_lte: String
  description_gt: String
  description_gte: String
  description_contains: String
  description_not_contains: String
  description_starts_with: String
  description_not_starts_with: String
  description_ends_with: String
  description_not_ends_with: String
  date: DateTime
  date_not: DateTime
  date_in: [DateTime!]
  date_not_in: [DateTime!]
  date_lt: DateTime
  date_lte: DateTime
  date_gt: DateTime
  date_gte: DateTime
  time: DateTime
  time_not: DateTime
  time_in: [DateTime!]
  time_not_in: [DateTime!]
  time_lt: DateTime
  time_lte: DateTime
  time_gt: DateTime
  time_gte: DateTime
  location: LocationWhereInput
  meetLocation: LocationWhereInput
  startDate: DateTime
  startDate_not: DateTime
  startDate_in: [DateTime!]
  startDate_not_in: [DateTime!]
  startDate_lt: DateTime
  startDate_lte: DateTime
  startDate_gt: DateTime
  startDate_gte: DateTime
  endDate: DateTime
  endDate_not: DateTime
  endDate_in: [DateTime!]
  endDate_not_in: [DateTime!]
  endDate_lt: DateTime
  endDate_lte: DateTime
  endDate_gt: DateTime
  endDate_gte: DateTime
  recurring: Boolean
  recurring_not: Boolean
  day: WEEK_DAY
  day_not: WEEK_DAY
  day_in: [WEEK_DAY!]
  day_not_in: [WEEK_DAY!]
  distance: Int
  distance_not: Int
  distance_in: [Int!]
  distance_not_in: [Int!]
  distance_lt: Int
  distance_lte: Int
  distance_gt: Int
  distance_gte: Int
  published: Boolean
  published_not: Boolean
  owner: UserWhereInput
  AND: [EventWhereInput!]
  OR: [EventWhereInput!]
  NOT: [EventWhereInput!]
}

input EventWhereUniqueInput {
  id: ID
}

type Location {
  lat: Float!
  lng: Float!
}

type LocationConnection {
  pageInfo: PageInfo!
  edges: [LocationEdge]!
  aggregate: AggregateLocation!
}

input LocationCreateInput {
  lat: Float!
  lng: Float!
}

input LocationCreateOneInput {
  create: LocationCreateInput
}

type LocationEdge {
  node: Location!
  cursor: String!
}

enum LocationOrderByInput {
  lat_ASC
  lat_DESC
  lng_ASC
  lng_DESC
}

type LocationPreviousValues {
  lat: Float!
  lng: Float!
}

type LocationSubscriptionPayload {
  mutation: MutationType!
  node: Location
  updatedFields: [String!]
  previousValues: LocationPreviousValues
}

input LocationSubscriptionWhereInput {
  mutation_in: [MutationType!]
  updatedFields_contains: String
  updatedFields_contains_every: [String!]
  updatedFields_contains_some: [String!]
  node: LocationWhereInput
  AND: [LocationSubscriptionWhereInput!]
  OR: [LocationSubscriptionWhereInput!]
  NOT: [LocationSubscriptionWhereInput!]
}

input LocationUpdateDataInput {
  lat: Float
  lng: Float
}

input LocationUpdateManyMutationInput {
  lat: Float
  lng: Float
}

input LocationUpdateOneInput {
  create: LocationCreateInput
  update: LocationUpdateDataInput
  upsert: LocationUpsertNestedInput
  delete: Boolean
  disconnect: Boolean
}

input LocationUpsertNestedInput {
  update: LocationUpdateDataInput!
  create: LocationCreateInput!
}

input LocationWhereInput {
  lat: Float
  lat_not: Float
  lat_in: [Float!]
  lat_not_in: [Float!]
  lat_lt: Float
  lat_lte: Float
  lat_gt: Float
  lat_gte: Float
  lng: Float
  lng_not: Float
  lng_in: [Float!]
  lng_not_in: [Float!]
  lng_lt: Float
  lng_lte: Float
  lng_gt: Float
  lng_gte: Float
  AND: [LocationWhereInput!]
  OR: [LocationWhereInput!]
  NOT: [LocationWhereInput!]
}

scalar Long

type Mutation {
  createEvent(data: EventCreateInput!): Event!
  updateEvent(data: EventUpdateInput!, where: EventWhereUniqueInput!): Event
  updateManyEvents(data: EventUpdateManyMutationInput!, where: EventWhereInput): BatchPayload!
  upsertEvent(where: EventWhereUniqueInput!, create: EventCreateInput!, update: EventUpdateInput!): Event!
  deleteEvent(where: EventWhereUniqueInput!): Event
  deleteManyEvents(where: EventWhereInput): BatchPayload!
  createLocation(data: LocationCreateInput!): Location!
  updateManyLocations(data: LocationUpdateManyMutationInput!, where: LocationWhereInput): BatchPayload!
  deleteManyLocations(where: LocationWhereInput): BatchPayload!
  createPatrol(data: PatrolCreateInput!): Patrol!
  updatePatrol(data: PatrolUpdateInput!, where: PatrolWhereUniqueInput!): Patrol
  updateManyPatrols(data: PatrolUpdateManyMutationInput!, where: PatrolWhereInput): BatchPayload!
  upsertPatrol(where: PatrolWhereUniqueInput!, create: PatrolCreateInput!, update: PatrolUpdateInput!): Patrol!
  deletePatrol(where: PatrolWhereUniqueInput!): Patrol
  deleteManyPatrols(where: PatrolWhereInput): BatchPayload!
  createTroop(data: TroopCreateInput!): Troop!
  updateTroop(data: TroopUpdateInput!, where: TroopWhereUniqueInput!): Troop
  updateManyTroops(data: TroopUpdateManyMutationInput!, where: TroopWhereInput): BatchPayload!
  upsertTroop(where: TroopWhereUniqueInput!, create: TroopCreateInput!, update: TroopUpdateInput!): Troop!
  deleteTroop(where: TroopWhereUniqueInput!): Troop
  deleteManyTroops(where: TroopWhereInput): BatchPayload!
  createUser(data: UserCreateInput!): User!
  updateUser(data: UserUpdateInput!, where: UserWhereUniqueInput!): User
  updateManyUsers(data: UserUpdateManyMutationInput!, where: UserWhereInput): BatchPayload!
  upsertUser(where: UserWhereUniqueInput!, create: UserCreateInput!, update: UserUpdateInput!): User!
  deleteUser(where: UserWhereUniqueInput!): User
  deleteManyUsers(where: UserWhereInput): BatchPayload!
}

enum MutationType {
  CREATED
  UPDATED
  DELETED
}

interface Node {
  id: ID!
}

type PageInfo {
  hasNextPage: Boolean!
  hasPreviousPage: Boolean!
  startCursor: String
  endCursor: String
}

type Patrol {
  id: ID!
  createdAt: DateTime!
  updatedAt: DateTime!
  name: String!
  members(where: UserWhereInput, orderBy: UserOrderByInput, skip: Int, after: String, before: String, first: Int, last: Int): [User!]
  events(where: EventWhereInput, orderBy: EventOrderByInput, skip: Int, after: String, before: String, first: Int, last: Int): [Event!]
}

type PatrolConnection {
  pageInfo: PageInfo!
  edges: [PatrolEdge]!
  aggregate: AggregatePatrol!
}

input PatrolCreateInput {
  id: ID
  name: String!
  members: UserCreateManyWithoutPatrolInput
  events: EventCreateManyWithoutPatrolInput
}

input PatrolCreateManyInput {
  create: [PatrolCreateInput!]
  connect: [PatrolWhereUniqueInput!]
}

input PatrolCreateOneWithoutEventsInput {
  create: PatrolCreateWithoutEventsInput
  connect: PatrolWhereUniqueInput
}

input PatrolCreateOneWithoutMembersInput {
  create: PatrolCreateWithoutMembersInput
  connect: PatrolWhereUniqueInput
}

input PatrolCreateWithoutEventsInput {
  id: ID
  name: String!
  members: UserCreateManyWithoutPatrolInput
}

input PatrolCreateWithoutMembersInput {
  id: ID
  name: String!
  events: EventCreateManyWithoutPatrolInput
}

type PatrolEdge {
  node: Patrol!
  cursor: String!
}

enum PatrolOrderByInput {
  id_ASC
  id_DESC
  createdAt_ASC
  createdAt_DESC
  updatedAt_ASC
  updatedAt_DESC
  name_ASC
  name_DESC
}

type PatrolPreviousValues {
  id: ID!
  createdAt: DateTime!
  updatedAt: DateTime!
  name: String!
}

input PatrolScalarWhereInput {
  id: ID
  id_not: ID
  id_in: [ID!]
  id_not_in: [ID!]
  id_lt: ID
  id_lte: ID
  id_gt: ID
  id_gte: ID
  id_contains: ID
  id_not_contains: ID
  id_starts_with: ID
  id_not_starts_with: ID
  id_ends_with: ID
  id_not_ends_with: ID
  createdAt: DateTime
  createdAt_not: DateTime
  createdAt_in: [DateTime!]
  createdAt_not_in: [DateTime!]
  createdAt_lt: DateTime
  createdAt_lte: DateTime
  createdAt_gt: DateTime
  createdAt_gte: DateTime
  updatedAt: DateTime
  updatedAt_not: DateTime
  updatedAt_in: [DateTime!]
  updatedAt_not_in: [DateTime!]
  updatedAt_lt: DateTime
  updatedAt_lte: DateTime
  updatedAt_gt: DateTime
  updatedAt_gte: DateTime
  name: String
  name_not: String
  name_in: [String!]
  name_not_in: [String!]
  name_lt: String
  name_lte: String
  name_gt: String
  name_gte: String
  name_contains: String
  name_not_contains: String
  name_starts_with: String
  name_not_starts_with: String
  name_ends_with: String
  name_not_ends_with: String
  AND: [PatrolScalarWhereInput!]
  OR: [PatrolScalarWhereInput!]
  NOT: [PatrolScalarWhereInput!]
}

type PatrolSubscriptionPayload {
  mutation: MutationType!
  node: Patrol
  updatedFields: [String!]
  previousValues: PatrolPreviousValues
}

input PatrolSubscriptionWhereInput {
  mutation_in: [MutationType!]
  updatedFields_contains: String
  updatedFields_contains_every: [String!]
  updatedFields_contains_some: [String!]
  node: PatrolWhereInput
  AND: [PatrolSubscriptionWhereInput!]
  OR: [PatrolSubscriptionWhereInput!]
  NOT: [PatrolSubscriptionWhereInput!]
}

input PatrolUpdateDataInput {
  name: String
  members: UserUpdateManyWithoutPatrolInput
  events: EventUpdateManyWithoutPatrolInput
}

input PatrolUpdateInput {
  name: String
  members: UserUpdateManyWithoutPatrolInput
  events: EventUpdateManyWithoutPatrolInput
}

input PatrolUpdateManyDataInput {
  name: String
}

input PatrolUpdateManyInput {
  create: [PatrolCreateInput!]
  update: [PatrolUpdateWithWhereUniqueNestedInput!]
  upsert: [PatrolUpsertWithWhereUniqueNestedInput!]
  delete: [PatrolWhereUniqueInput!]
  connect: [PatrolWhereUniqueInput!]
  set: [PatrolWhereUniqueInput!]
  disconnect: [PatrolWhereUniqueInput!]
  deleteMany: [PatrolScalarWhereInput!]
  updateMany: [PatrolUpdateManyWithWhereNestedInput!]
}

input PatrolUpdateManyMutationInput {
  name: String
}

input PatrolUpdateManyWithWhereNestedInput {
  where: PatrolScalarWhereInput!
  data: PatrolUpdateManyDataInput!
}

input PatrolUpdateOneWithoutEventsInput {
  create: PatrolCreateWithoutEventsInput
  update: PatrolUpdateWithoutEventsDataInput
  upsert: PatrolUpsertWithoutEventsInput
  delete: Boolean
  disconnect: Boolean
  connect: PatrolWhereUniqueInput
}

input PatrolUpdateOneWithoutMembersInput {
  create: PatrolCreateWithoutMembersInput
  update: PatrolUpdateWithoutMembersDataInput
  upsert: PatrolUpsertWithoutMembersInput
  delete: Boolean
  disconnect: Boolean
  connect: PatrolWhereUniqueInput
}

input PatrolUpdateWithoutEventsDataInput {
  name: String
  members: UserUpdateManyWithoutPatrolInput
}

input PatrolUpdateWithoutMembersDataInput {
  name: String
  events: EventUpdateManyWithoutPatrolInput
}

input PatrolUpdateWithWhereUniqueNestedInput {
  where: PatrolWhereUniqueInput!
  data: PatrolUpdateDataInput!
}

input PatrolUpsertWithoutEventsInput {
  update: PatrolUpdateWithoutEventsDataInput!
  create: PatrolCreateWithoutEventsInput!
}

input PatrolUpsertWithoutMembersInput {
  update: PatrolUpdateWithoutMembersDataInput!
  create: PatrolCreateWithoutMembersInput!
}

input PatrolUpsertWithWhereUniqueNestedInput {
  where: PatrolWhereUniqueInput!
  update: PatrolUpdateDataInput!
  create: PatrolCreateInput!
}

input PatrolWhereInput {
  id: ID
  id_not: ID
  id_in: [ID!]
  id_not_in: [ID!]
  id_lt: ID
  id_lte: ID
  id_gt: ID
  id_gte: ID
  id_contains: ID
  id_not_contains: ID
  id_starts_with: ID
  id_not_starts_with: ID
  id_ends_with: ID
  id_not_ends_with: ID
  createdAt: DateTime
  createdAt_not: DateTime
  createdAt_in: [DateTime!]
  createdAt_not_in: [DateTime!]
  createdAt_lt: DateTime
  createdAt_lte: DateTime
  createdAt_gt: DateTime
  createdAt_gte: DateTime
  updatedAt: DateTime
  updatedAt_not: DateTime
  updatedAt_in: [DateTime!]
  updatedAt_not_in: [DateTime!]
  updatedAt_lt: DateTime
  updatedAt_lte: DateTime
  updatedAt_gt: DateTime
  updatedAt_gte: DateTime
  name: String
  name_not: String
  name_in: [String!]
  name_not_in: [String!]
  name_lt: String
  name_lte: String
  name_gt: String
  name_gte: String
  name_contains: String
  name_not_contains: String
  name_starts_with: String
  name_not_starts_with: String
  name_ends_with: String
  name_not_ends_with: String
  members_every: UserWhereInput
  members_some: UserWhereInput
  members_none: UserWhereInput
  events_every: EventWhereInput
  events_some: EventWhereInput
  events_none: EventWhereInput
  AND: [PatrolWhereInput!]
  OR: [PatrolWhereInput!]
  NOT: [PatrolWhereInput!]
}

input PatrolWhereUniqueInput {
  id: ID
}

type Query {
  event(where: EventWhereUniqueInput!): Event
  events(where: EventWhereInput, orderBy: EventOrderByInput, skip: Int, after: String, before: String, first: Int, last: Int): [Event]!
  eventsConnection(where: EventWhereInput, orderBy: EventOrderByInput, skip: Int, after: String, before: String, first: Int, last: Int): EventConnection!
  locations(where: LocationWhereInput, orderBy: LocationOrderByInput, skip: Int, after: String, before: String, first: Int, last: Int): [Location]!
  locationsConnection(where: LocationWhereInput, orderBy: LocationOrderByInput, skip: Int, after: String, before: String, first: Int, last: Int): LocationConnection!
  patrol(where: PatrolWhereUniqueInput!): Patrol
  patrols(where: PatrolWhereInput, orderBy: PatrolOrderByInput, skip: Int, after: String, before: String, first: Int, last: Int): [Patrol]!
  patrolsConnection(where: PatrolWhereInput, orderBy: PatrolOrderByInput, skip: Int, after: String, before: String, first: Int, last: Int): PatrolConnection!
  troop(where: TroopWhereUniqueInput!): Troop
  troops(where: TroopWhereInput, orderBy: TroopOrderByInput, skip: Int, after: String, before: String, first: Int, last: Int): [Troop]!
  troopsConnection(where: TroopWhereInput, orderBy: TroopOrderByInput, skip: Int, after: String, before: String, first: Int, last: Int): TroopConnection!
  user(where: UserWhereUniqueInput!): User
  users(where: UserWhereInput, orderBy: UserOrderByInput, skip: Int, after: String, before: String, first: Int, last: Int): [User]!
  usersConnection(where: UserWhereInput, orderBy: UserOrderByInput, skip: Int, after: String, before: String, first: Int, last: Int): UserConnection!
  node(id: ID!): Node
}

enum ROLE {
  SCOUT_MASTER
  SR_PATROL_LEADER
  PATROL_LEADER
  SCOUT
  PARENT
}

type Subscription {
  event(where: EventSubscriptionWhereInput): EventSubscriptionPayload
  location(where: LocationSubscriptionWhereInput): LocationSubscriptionPayload
  patrol(where: PatrolSubscriptionWhereInput): PatrolSubscriptionPayload
  troop(where: TroopSubscriptionWhereInput): TroopSubscriptionPayload
  user(where: UserSubscriptionWhereInput): UserSubscriptionPayload
}

type Troop {
  id: ID!
  createdAt: DateTime!
  updatedAt: DateTime!
  council: String!
  state: String!
  unitNumber: Int
  patrols(where: PatrolWhereInput, orderBy: PatrolOrderByInput, skip: Int, after: String, before: String, first: Int, last: Int): [Patrol!]
  events(where: EventWhereInput, orderBy: EventOrderByInput, skip: Int, after: String, before: String, first: Int, last: Int): [Event!]
}

type TroopConnection {
  pageInfo: PageInfo!
  edges: [TroopEdge]!
  aggregate: AggregateTroop!
}

input TroopCreateInput {
  id: ID
  council: String!
  state: String!
  unitNumber: Int
  patrols: PatrolCreateManyInput
  events: EventCreateManyWithoutTroopInput
}

input TroopCreateOneInput {
  create: TroopCreateInput
  connect: TroopWhereUniqueInput
}

input TroopCreateOneWithoutEventsInput {
  create: TroopCreateWithoutEventsInput
  connect: TroopWhereUniqueInput
}

input TroopCreateWithoutEventsInput {
  id: ID
  council: String!
  state: String!
  unitNumber: Int
  patrols: PatrolCreateManyInput
}

type TroopEdge {
  node: Troop!
  cursor: String!
}

enum TroopOrderByInput {
  id_ASC
  id_DESC
  createdAt_ASC
  createdAt_DESC
  updatedAt_ASC
  updatedAt_DESC
  council_ASC
  council_DESC
  state_ASC
  state_DESC
  unitNumber_ASC
  unitNumber_DESC
}

type TroopPreviousValues {
  id: ID!
  createdAt: DateTime!
  updatedAt: DateTime!
  council: String!
  state: String!
  unitNumber: Int
}

type TroopSubscriptionPayload {
  mutation: MutationType!
  node: Troop
  updatedFields: [String!]
  previousValues: TroopPreviousValues
}

input TroopSubscriptionWhereInput {
  mutation_in: [MutationType!]
  updatedFields_contains: String
  updatedFields_contains_every: [String!]
  updatedFields_contains_some: [String!]
  node: TroopWhereInput
  AND: [TroopSubscriptionWhereInput!]
  OR: [TroopSubscriptionWhereInput!]
  NOT: [TroopSubscriptionWhereInput!]
}

input TroopUpdateDataInput {
  council: String
  state: String
  unitNumber: Int
  patrols: PatrolUpdateManyInput
  events: EventUpdateManyWithoutTroopInput
}

input TroopUpdateInput {
  council: String
  state: String
  unitNumber: Int
  patrols: PatrolUpdateManyInput
  events: EventUpdateManyWithoutTroopInput
}

input TroopUpdateManyMutationInput {
  council: String
  state: String
  unitNumber: Int
}

input TroopUpdateOneInput {
  create: TroopCreateInput
  update: TroopUpdateDataInput
  upsert: TroopUpsertNestedInput
  delete: Boolean
  disconnect: Boolean
  connect: TroopWhereUniqueInput
}

input TroopUpdateOneWithoutEventsInput {
  create: TroopCreateWithoutEventsInput
  update: TroopUpdateWithoutEventsDataInput
  upsert: TroopUpsertWithoutEventsInput
  delete: Boolean
  disconnect: Boolean
  connect: TroopWhereUniqueInput
}

input TroopUpdateWithoutEventsDataInput {
  council: String
  state: String
  unitNumber: Int
  patrols: PatrolUpdateManyInput
}

input TroopUpsertNestedInput {
  update: TroopUpdateDataInput!
  create: TroopCreateInput!
}

input TroopUpsertWithoutEventsInput {
  update: TroopUpdateWithoutEventsDataInput!
  create: TroopCreateWithoutEventsInput!
}

input TroopWhereInput {
  id: ID
  id_not: ID
  id_in: [ID!]
  id_not_in: [ID!]
  id_lt: ID
  id_lte: ID
  id_gt: ID
  id_gte: ID
  id_contains: ID
  id_not_contains: ID
  id_starts_with: ID
  id_not_starts_with: ID
  id_ends_with: ID
  id_not_ends_with: ID
  createdAt: DateTime
  createdAt_not: DateTime
  createdAt_in: [DateTime!]
  createdAt_not_in: [DateTime!]
  createdAt_lt: DateTime
  createdAt_lte: DateTime
  createdAt_gt: DateTime
  createdAt_gte: DateTime
  updatedAt: DateTime
  updatedAt_not: DateTime
  updatedAt_in: [DateTime!]
  updatedAt_not_in: [DateTime!]
  updatedAt_lt: DateTime
  updatedAt_lte: DateTime
  updatedAt_gt: DateTime
  updatedAt_gte: DateTime
  council: String
  council_not: String
  council_in: [String!]
  council_not_in: [String!]
  council_lt: String
  council_lte: String
  council_gt: String
  council_gte: String
  council_contains: String
  council_not_contains: String
  council_starts_with: String
  council_not_starts_with: String
  council_ends_with: String
  council_not_ends_with: String
  state: String
  state_not: String
  state_in: [String!]
  state_not_in: [String!]
  state_lt: String
  state_lte: String
  state_gt: String
  state_gte: String
  state_contains: String
  state_not_contains: String
  state_starts_with: String
  state_not_starts_with: String
  state_ends_with: String
  state_not_ends_with: String
  unitNumber: Int
  unitNumber_not: Int
  unitNumber_in: [Int!]
  unitNumber_not_in: [Int!]
  unitNumber_lt: Int
  unitNumber_lte: Int
  unitNumber_gt: Int
  unitNumber_gte: Int
  patrols_every: PatrolWhereInput
  patrols_some: PatrolWhereInput
  patrols_none: PatrolWhereInput
  events_every: EventWhereInput
  events_some: EventWhereInput
  events_none: EventWhereInput
  AND: [TroopWhereInput!]
  OR: [TroopWhereInput!]
  NOT: [TroopWhereInput!]
}

input TroopWhereUniqueInput {
  id: ID
}

type User {
  id: ID!
  createdAt: DateTime!
  updatedAt: DateTime!
  name: String!
  email: String!
  password: String!
  phone: String
  birthday: String
  troop: Troop
  patrol: Patrol
  role: ROLE
  events(where: EventWhereInput, orderBy: EventOrderByInput, skip: Int, after: String, before: String, first: Int, last: Int): [Event!]
}

type UserConnection {
  pageInfo: PageInfo!
  edges: [UserEdge]!
  aggregate: AggregateUser!
}

input UserCreateInput {
  id: ID
  name: String!
  email: String!
  password: String!
  phone: String
  birthday: String
  troop: TroopCreateOneInput
  patrol: PatrolCreateOneWithoutMembersInput
  role: ROLE
  events: EventCreateManyWithoutOwnerInput
}

input UserCreateManyWithoutPatrolInput {
  create: [UserCreateWithoutPatrolInput!]
  connect: [UserWhereUniqueInput!]
}

input UserCreateOneWithoutEventsInput {
  create: UserCreateWithoutEventsInput
  connect: UserWhereUniqueInput
}

input UserCreateWithoutEventsInput {
  id: ID
  name: String!
  email: String!
  password: String!
  phone: String
  birthday: String
  troop: TroopCreateOneInput
  patrol: PatrolCreateOneWithoutMembersInput
  role: ROLE
}

input UserCreateWithoutPatrolInput {
  id: ID
  name: String!
  email: String!
  password: String!
  phone: String
  birthday: String
  troop: TroopCreateOneInput
  role: ROLE
  events: EventCreateManyWithoutOwnerInput
}

type UserEdge {
  node: User!
  cursor: String!
}

enum UserOrderByInput {
  id_ASC
  id_DESC
  createdAt_ASC
  createdAt_DESC
  updatedAt_ASC
  updatedAt_DESC
  name_ASC
  name_DESC
  email_ASC
  email_DESC
  password_ASC
  password_DESC
  phone_ASC
  phone_DESC
  birthday_ASC
  birthday_DESC
  role_ASC
  role_DESC
}

type UserPreviousValues {
  id: ID!
  createdAt: DateTime!
  updatedAt: DateTime!
  name: String!
  email: String!
  password: String!
  phone: String
  birthday: String
  role: ROLE
}

input UserScalarWhereInput {
  id: ID
  id_not: ID
  id_in: [ID!]
  id_not_in: [ID!]
  id_lt: ID
  id_lte: ID
  id_gt: ID
  id_gte: ID
  id_contains: ID
  id_not_contains: ID
  id_starts_with: ID
  id_not_starts_with: ID
  id_ends_with: ID
  id_not_ends_with: ID
  createdAt: DateTime
  createdAt_not: DateTime
  createdAt_in: [DateTime!]
  createdAt_not_in: [DateTime!]
  createdAt_lt: DateTime
  createdAt_lte: DateTime
  createdAt_gt: DateTime
  createdAt_gte: DateTime
  updatedAt: DateTime
  updatedAt_not: DateTime
  updatedAt_in: [DateTime!]
  updatedAt_not_in: [DateTime!]
  updatedAt_lt: DateTime
  updatedAt_lte: DateTime
  updatedAt_gt: DateTime
  updatedAt_gte: DateTime
  name: String
  name_not: String
  name_in: [String!]
  name_not_in: [String!]
  name_lt: String
  name_lte: String
  name_gt: String
  name_gte: String
  name_contains: String
  name_not_contains: String
  name_starts_with: String
  name_not_starts_with: String
  name_ends_with: String
  name_not_ends_with: String
  email: String
  email_not: String
  email_in: [String!]
  email_not_in: [String!]
  email_lt: String
  email_lte: String
  email_gt: String
  email_gte: String
  email_contains: String
  email_not_contains: String
  email_starts_with: String
  email_not_starts_with: String
  email_ends_with: String
  email_not_ends_with: String
  password: String
  password_not: String
  password_in: [String!]
  password_not_in: [String!]
  password_lt: String
  password_lte: String
  password_gt: String
  password_gte: String
  password_contains: String
  password_not_contains: String
  password_starts_with: String
  password_not_starts_with: String
  password_ends_with: String
  password_not_ends_with: String
  phone: String
  phone_not: String
  phone_in: [String!]
  phone_not_in: [String!]
  phone_lt: String
  phone_lte: String
  phone_gt: String
  phone_gte: String
  phone_contains: String
  phone_not_contains: String
  phone_starts_with: String
  phone_not_starts_with: String
  phone_ends_with: String
  phone_not_ends_with: String
  birthday: String
  birthday_not: String
  birthday_in: [String!]
  birthday_not_in: [String!]
  birthday_lt: String
  birthday_lte: String
  birthday_gt: String
  birthday_gte: String
  birthday_contains: String
  birthday_not_contains: String
  birthday_starts_with: String
  birthday_not_starts_with: String
  birthday_ends_with: String
  birthday_not_ends_with: String
  role: ROLE
  role_not: ROLE
  role_in: [ROLE!]
  role_not_in: [ROLE!]
  AND: [UserScalarWhereInput!]
  OR: [UserScalarWhereInput!]
  NOT: [UserScalarWhereInput!]
}

type UserSubscriptionPayload {
  mutation: MutationType!
  node: User
  updatedFields: [String!]
  previousValues: UserPreviousValues
}

input UserSubscriptionWhereInput {
  mutation_in: [MutationType!]
  updatedFields_contains: String
  updatedFields_contains_every: [String!]
  updatedFields_contains_some: [String!]
  node: UserWhereInput
  AND: [UserSubscriptionWhereInput!]
  OR: [UserSubscriptionWhereInput!]
  NOT: [UserSubscriptionWhereInput!]
}

input UserUpdateInput {
  name: String
  email: String
  password: String
  phone: String
  birthday: String
  troop: TroopUpdateOneInput
  patrol: PatrolUpdateOneWithoutMembersInput
  role: ROLE
  events: EventUpdateManyWithoutOwnerInput
}

input UserUpdateManyDataInput {
  name: String
  email: String
  password: String
  phone: String
  birthday: String
  role: ROLE
}

input UserUpdateManyMutationInput {
  name: String
  email: String
  password: String
  phone: String
  birthday: String
  role: ROLE
}

input UserUpdateManyWithoutPatrolInput {
  create: [UserCreateWithoutPatrolInput!]
  delete: [UserWhereUniqueInput!]
  connect: [UserWhereUniqueInput!]
  set: [UserWhereUniqueInput!]
  disconnect: [UserWhereUniqueInput!]
  update: [UserUpdateWithWhereUniqueWithoutPatrolInput!]
  upsert: [UserUpsertWithWhereUniqueWithoutPatrolInput!]
  deleteMany: [UserScalarWhereInput!]
  updateMany: [UserUpdateManyWithWhereNestedInput!]
}

input UserUpdateManyWithWhereNestedInput {
  where: UserScalarWhereInput!
  data: UserUpdateManyDataInput!
}

input UserUpdateOneRequiredWithoutEventsInput {
  create: UserCreateWithoutEventsInput
  update: UserUpdateWithoutEventsDataInput
  upsert: UserUpsertWithoutEventsInput
  connect: UserWhereUniqueInput
}

input UserUpdateWithoutEventsDataInput {
  name: String
  email: String
  password: String
  phone: String
  birthday: String
  troop: TroopUpdateOneInput
  patrol: PatrolUpdateOneWithoutMembersInput
  role: ROLE
}

input UserUpdateWithoutPatrolDataInput {
  name: String
  email: String
  password: String
  phone: String
  birthday: String
  troop: TroopUpdateOneInput
  role: ROLE
  events: EventUpdateManyWithoutOwnerInput
}

input UserUpdateWithWhereUniqueWithoutPatrolInput {
  where: UserWhereUniqueInput!
  data: UserUpdateWithoutPatrolDataInput!
}

input UserUpsertWithoutEventsInput {
  update: UserUpdateWithoutEventsDataInput!
  create: UserCreateWithoutEventsInput!
}

input UserUpsertWithWhereUniqueWithoutPatrolInput {
  where: UserWhereUniqueInput!
  update: UserUpdateWithoutPatrolDataInput!
  create: UserCreateWithoutPatrolInput!
}

input UserWhereInput {
  id: ID
  id_not: ID
  id_in: [ID!]
  id_not_in: [ID!]
  id_lt: ID
  id_lte: ID
  id_gt: ID
  id_gte: ID
  id_contains: ID
  id_not_contains: ID
  id_starts_with: ID
  id_not_starts_with: ID
  id_ends_with: ID
  id_not_ends_with: ID
  createdAt: DateTime
  createdAt_not: DateTime
  createdAt_in: [DateTime!]
  createdAt_not_in: [DateTime!]
  createdAt_lt: DateTime
  createdAt_lte: DateTime
  createdAt_gt: DateTime
  createdAt_gte: DateTime
  updatedAt: DateTime
  updatedAt_not: DateTime
  updatedAt_in: [DateTime!]
  updatedAt_not_in: [DateTime!]
  updatedAt_lt: DateTime
  updatedAt_lte: DateTime
  updatedAt_gt: DateTime
  updatedAt_gte: DateTime
  name: String
  name_not: String
  name_in: [String!]
  name_not_in: [String!]
  name_lt: String
  name_lte: String
  name_gt: String
  name_gte: String
  name_contains: String
  name_not_contains: String
  name_starts_with: String
  name_not_starts_with: String
  name_ends_with: String
  name_not_ends_with: String
  email: String
  email_not: String
  email_in: [String!]
  email_not_in: [String!]
  email_lt: String
  email_lte: String
  email_gt: String
  email_gte: String
  email_contains: String
  email_not_contains: String
  email_starts_with: String
  email_not_starts_with: String
  email_ends_with: String
  email_not_ends_with: String
  password: String
  password_not: String
  password_in: [String!]
  password_not_in: [String!]
  password_lt: String
  password_lte: String
  password_gt: String
  password_gte: String
  password_contains: String
  password_not_contains: String
  password_starts_with: String
  password_not_starts_with: String
  password_ends_with: String
  password_not_ends_with: String
  phone: String
  phone_not: String
  phone_in: [String!]
  phone_not_in: [String!]
  phone_lt: String
  phone_lte: String
  phone_gt: String
  phone_gte: String
  phone_contains: String
  phone_not_contains: String
  phone_starts_with: String
  phone_not_starts_with: String
  phone_ends_with: String
  phone_not_ends_with: String
  birthday: String
  birthday_not: String
  birthday_in: [String!]
  birthday_not_in: [String!]
  birthday_lt: String
  birthday_lte: String
  birthday_gt: String
  birthday_gte: String
  birthday_contains: String
  birthday_not_contains: String
  birthday_starts_with: String
  birthday_not_starts_with: String
  birthday_ends_with: String
  birthday_not_ends_with: String
  troop: TroopWhereInput
  patrol: PatrolWhereInput
  role: ROLE
  role_not: ROLE
  role_in: [ROLE!]
  role_not_in: [ROLE!]
  events_every: EventWhereInput
  events_some: EventWhereInput
  events_none: EventWhereInput
  AND: [UserWhereInput!]
  OR: [UserWhereInput!]
  NOT: [UserWhereInput!]
}

input UserWhereUniqueInput {
  id: ID
  email: String
}

enum WEEK_DAY {
  SUNDAY
  MONDAY
  TUESDAY
  WEDNESDAY
  THURSDAY
  FRIDAY
  SATURDAY
}
`
      }
    